#!/usr/bin/env node
/**
 * Risto CRM — Interactive Setup Script
 * ──────────────────────────────────────────────────────────────────────────
 * Run:  node setup.js
 *
 * This script guides you through the first-time configuration:
 *   1. Supabase project URL + anon key
 *   2. App name and owner info
 *   3. Number of restaurant locations (sedi)
 *   4. Vercel deployment (optional)
 *
 * Output: client/.env.local   ← never committed to git
 *         .setup_done          ← marker file
 * ──────────────────────────────────────────────────────────────────────────
 */

const readline = require('readline')
const fs       = require('fs')
const path     = require('path')
const https    = require('https')

const ENV_PATH  = path.join(__dirname, 'client', '.env.local')
const DONE_PATH = path.join(__dirname, '.setup_done')

// ─── Colors ──────────────────────────────────────────────────────────────
const c = {
  reset:  '\x1b[0m',
  bold:   '\x1b[1m',
  dim:    '\x1b[2m',
  green:  '\x1b[32m',
  blue:   '\x1b[34m',
  yellow: '\x1b[33m',
  red:    '\x1b[31m',
  cyan:   '\x1b[36m',
  violet: '\x1b[35m',
}
const ok  = (s) => console.log(`${c.green}  ✓${c.reset} ${s}`)
const err = (s) => console.log(`${c.red}  ✗${c.reset} ${s}`)
const tip = (s) => console.log(`${c.dim}    ${s}${c.reset}`)
const hdr = (s) => console.log(`\n${c.bold}${c.violet}━━  ${s}  ━━${c.reset}\n`)

// ─── Readline helpers ────────────────────────────────────────────────────
const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

function ask(question, defaultVal = '') {
  return new Promise(resolve => {
    const hint = defaultVal ? ` ${c.dim}[${defaultVal}]${c.reset}` : ''
    rl.question(`  ${question}${hint}: `, (answer) => {
      resolve(answer.trim() || defaultVal)
    })
  })
}

function askSecret(question) {
  return new Promise(resolve => {
    process.stdout.write(`  ${question}: `)
    process.stdin.setRawMode?.(true)
    let input = ''
    process.stdin.resume()
    process.stdin.setEncoding('utf8')

    const onData = (ch) => {
      if (ch === '\n' || ch === '\r' || ch === '') {
        process.stdin.setRawMode?.(false)
        process.stdin.pause()
        process.stdin.removeListener('data', onData)
        process.stdout.write('\n')
        resolve(input)
      } else if (ch === '' || ch === '') {
        if (input.length > 0) {
          input = input.slice(0, -1)
          process.stdout.write('\b \b')
        }
      } else {
        input += ch
        process.stdout.write('*')
      }
    }

    process.stdin.on('data', onData)
  })
}

function askYesNo(question, defaultYes = true) {
  const hint = defaultYes ? 'Y/n' : 'y/N'
  return new Promise(resolve => {
    rl.question(`  ${question} ${c.dim}[${hint}]${c.reset}: `, (answer) => {
      const a = answer.trim().toLowerCase()
      if (a === '') resolve(defaultYes)
      else resolve(a === 'y' || a === 'yes' || a === 's' || a === 'si')
    })
  })
}

// ─── Supabase connection test ─────────────────────────────────────────────
function testSupabase(url, anonKey) {
  return new Promise((resolve) => {
    const cleanUrl = url.replace(/\/$/, '')
    const options = {
      method: 'GET',
      headers: {
        'apikey': anonKey,
        'Authorization': `Bearer ${anonKey}`,
      },
    }
    const req = https.request(`${cleanUrl}/rest/v1/`, options, (res) => {
      resolve(res.statusCode === 200 || res.statusCode === 404)
    })
    req.on('error', () => resolve(false))
    req.setTimeout(5000, () => { req.destroy(); resolve(false) })
    req.end()
  })
}

// ─── Write .env.local ────────────────────────────────────────────────────
function writeEnv(vars) {
  const lines = [
    `# Risto CRM — Local Environment`,
    `# Generated by setup.js on ${new Date().toISOString().slice(0, 10)}`,
    `# ⚠️  DO NOT commit this file to git!`,
    ``,
    `# ── Supabase ────────────────────────────────────────────────────────`,
    `VITE_SUPABASE_URL=${vars.supabaseUrl}`,
    `VITE_SUPABASE_ANON_KEY=${vars.supabaseAnonKey}`,
    ``,
    `# ── App ─────────────────────────────────────────────────────────────`,
    `VITE_APP_NAME=${vars.appName}`,
    ``,
  ]

  if (vars.anthropicKey) {
    lines.push(`# ── Claude AI (optional — add to Vercel env vars, not here) ─────────`)
    lines.push(`# ANTHROPIC_API_KEY=${vars.anthropicKey}`)
    lines.push(``)
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')
}

// ─── Main ─────────────────────────────────────────────────────────────────
async function main() {
  console.clear()
  console.log(`
${c.bold}${c.violet}╔══════════════════════════════════════════════════════╗
║   🍽️  RISTO CRM — First-time Setup                  ║
║   Open-source restaurant management system           ║
╚══════════════════════════════════════════════════════╝${c.reset}

This script creates your ${c.bold}client/.env.local${c.reset} file.
Your credentials are ${c.bold}never${c.reset} committed to git.

${c.dim}Press Ctrl+C at any time to cancel.${c.reset}
`)

  // ── Step 1: Supabase ──────────────────────────────────────────────────
  hdr('Step 1 of 4 — Supabase Connection')
  console.log(`  Create a free project at ${c.cyan}https://supabase.com${c.reset}`)
  console.log(`  Then go to: Project Settings → API`)
  console.log()

  let supabaseUrl, supabaseAnonKey, connected = false

  while (!connected) {
    supabaseUrl     = await ask('Project URL', 'https://your-project.supabase.co')
    supabaseAnonKey = await ask('Anon/public key')

    if (!supabaseUrl.startsWith('https://') || !supabaseAnonKey) {
      err('Invalid URL or key. Try again.')
      continue
    }

    process.stdout.write(`\n  Testing connection...`)
    connected = await testSupabase(supabaseUrl, supabaseAnonKey)

    if (connected) {
      console.log(` ${c.green}connected!${c.reset}`)
      ok('Supabase project reachable')
    } else {
      console.log(` ${c.red}failed${c.reset}`)
      err('Cannot reach Supabase. Check URL and key.')
      const retry = await askYesNo('Try again?', true)
      if (!retry) {
        console.log(`\n${c.yellow}  Setup cancelled. Run node setup.js again when ready.${c.reset}\n`)
        process.exit(0)
      }
    }
  }

  // ── Step 2: App Info ──────────────────────────────────────────────────
  hdr('Step 2 of 4 — App & Restaurant Info')

  const appName   = await ask('Restaurant / Group name (shown in the app)', 'My Restaurant CRM')
  const ownerName = await ask('Your name')
  const ownerEmail = await ask('Your email')

  ok(`App name: ${c.bold}${appName}${c.reset}`)

  // ── Step 3: Sedi ──────────────────────────────────────────────────────
  hdr('Step 3 of 4 — Restaurant Locations (Sedi)')
  console.log(`  You can manage ${c.bold}multiple locations${c.reset} from a single CRM.`)
  console.log(`  Each location needs a short code (2-4 chars) and a name.\n`)

  const sedi = []
  let addMore = true

  while (addMore) {
    const n = sedi.length + 1
    console.log(`  ${c.bold}Location ${n}${c.reset}`)
    const code = await ask('  Code (e.g. MI, S1, CENTRO)', sedi.length === 0 ? 'S1' : `S${n}`)
    const name = await ask('  Full name (e.g. Milano Centro)', '')
    const city = await ask('  City', '')
    sedi.push({ code: code.toUpperCase(), name, city })
    ok(`Added: ${code.toUpperCase()} — ${name}`)

    if (sedi.length < 10) {
      addMore = await askYesNo('\n  Add another location?', false)
    } else {
      addMore = false
    }
    console.log()
  }

  // ── Step 4: Claude AI (optional) ─────────────────────────────────────
  hdr('Step 4 of 4 — Claude AI (Optional)')
  console.log(`  The Chat AI module uses Anthropic Claude.`)
  console.log(`  Get a free key at ${c.cyan}https://console.anthropic.com${c.reset}`)
  console.log(`  ${c.yellow}Important:${c.reset} Add ANTHROPIC_API_KEY to Vercel env vars, NOT to .env.local`)
  console.log()

  const hasAnthropic = await askYesNo('Do you have an Anthropic API key?', false)
  let anthropicKey = ''
  if (hasAnthropic) {
    anthropicKey = await ask('Anthropic API key (will be added as a comment only)')
    ok('Key noted — remember to add it to Vercel environment variables')
  }

  // ── Write .env.local ──────────────────────────────────────────────────
  hdr('Writing Configuration')

  writeEnv({ supabaseUrl, supabaseAnonKey, appName, ownerName, ownerEmail, anthropicKey })
  ok(`Created: ${c.bold}client/.env.local${c.reset}`)

  // ── Next steps ────────────────────────────────────────────────────────
  console.log(`
${c.bold}${c.green}╔══════════════════════════════════════════════════════╗
║   ✅  Setup complete!                                ║
╚══════════════════════════════════════════════════════╝${c.reset}

${c.bold}Next steps:${c.reset}

  1. ${c.cyan}Set up the database${c.reset}
     → Go to your Supabase project → SQL Editor
     → Run ${c.bold}supabase/schema.sql${c.reset} (all tables & views)
     → Run ${c.bold}supabase/seed.sql${c.reset} (default categories & modules)

  2. ${c.cyan}Start the app locally${c.reset}
     ${c.dim}cd client${c.reset}
     ${c.dim}npm install${c.reset}
     ${c.dim}npm run dev${c.reset}
     → Open ${c.bold}http://localhost:5173${c.reset}
     → The Setup Wizard will guide you through the rest

  3. ${c.cyan}Deploy to Vercel (free)${c.reset}
     ${c.dim}npm install -g vercel${c.reset}
     ${c.dim}vercel deploy --prod${c.reset} (run from repo root)
     → In Vercel dashboard, add env vars from client/.env.local
     ${c.yellow}→ Never add .env.local to Vercel — enter values manually${c.reset}

${c.dim}Full guide: README.md | Issues: github.com/AndyTrust/RISTO-CRM-Ai/issues${c.reset}
`)

  rl.close()
  fs.writeFileSync(DONE_PATH, new Date().toISOString(), 'utf8')
}

main().catch(e => {
  console.error(`\n${c.red}Error:${c.reset}`, e.message)
  process.exit(1)
})
