/**
 * client.js
 * Adapter API — tutto via Supabase (dev + prod).
 * Il vecchio client Express è in express-client.js.bak se serve.
 */
export {
  modules,
  employees,
  kpi,
  venduto,
  chiusure,
  fornitori,
  chat,
  data,
  analytics,
  bustePaga,
  statistiche,
  turni,
  roles,
  admin,
  crmConfig,
  sediApi,
  operatorMapping,
  pagamentiFatture,
  prodottiCatalogo,
  repartiApi,
  fattureBi,
  fattureCategorieApi,
  costiFissiApi,
  standardNazionaliApi,
  kpiTargetsApi,
  kpiPerformanceApi,
  beMensileApi,
  operatoreMeseApi,
  obiettiviProdottoApi,
  bonusApi,
  calcBonusTeam,
  calcBonusIndividuale,
  verificaApi,
  default,
} from './supabase-client'
